apiVersion: v1
kind: Service
metadata:
  name: mern-server
  namespace: default
spec:
  selector:
    app: mern-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: mern-client
  namespace: default
spec:
  selector:
    app: mern-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
